// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type MusicSession struct {
	ID     int64
	Data   string
	Active int64
	Type   string
	Uid    int64
}

type Scrobble struct {
	ID          int64
	ArtistName  string
	TrackName   string
	AlbumName   sql.NullString
	AlbumArtist sql.NullString
	TrackNumber sql.NullString
	Duration    int64
	Timestamp   int64
	Source      sql.NullString
	Mbid        sql.NullString
	Uid         int64
}

type Session struct {
	Accesstoken  string
	Refreshtoken string
	Valid        sql.NullInt64
}

type User struct {
	ID                   int64
	Username             string
	SpotifyAccessToken   sql.NullString
	SpotifyRefreshToken  sql.NullString
	LastfmSessionName    sql.NullString
	LastfmSessionKey     sql.NullString
	Password             interface{}
	TwitterRequestToken  sql.NullString
	TwitterRequestSecret sql.NullString
	TwitterOauthToken    sql.NullString
	TwitterOauthSecret   sql.NullString
}
