// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type User struct {
	ID                  int64
	Username            string
	SpotifyAccessToken  sql.NullString
	SpotifyRefreshToken sql.NullString
	LastfmSessionName   sql.NullString
	LastfmSessionKey    sql.NullString
}
