// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const getLastFMSession = `-- name: GetLastFMSession :one
SELECT lastfm_session_name, lastfm_session_key
FROM users
WHERE username = ?
`

type GetLastFMSessionRow struct {
	LastfmSessionName sql.NullString
	LastfmSessionKey  sql.NullString
}

func (q *Queries) GetLastFMSession(ctx context.Context, username string) (GetLastFMSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getLastFMSession, username)
	var i GetLastFMSessionRow
	err := row.Scan(&i.LastfmSessionName, &i.LastfmSessionKey)
	return i, err
}

const getSpotifySession = `-- name: GetSpotifySession :one
SELECT spotify_access_token, spotify_refresh_token
FROM users
WHERE username = ?
`

type GetSpotifySessionRow struct {
	SpotifyAccessToken  sql.NullString
	SpotifyRefreshToken sql.NullString
}

func (q *Queries) GetSpotifySession(ctx context.Context, username string) (GetSpotifySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSpotifySession, username)
	var i GetSpotifySessionRow
	err := row.Scan(&i.SpotifyAccessToken, &i.SpotifyRefreshToken)
	return i, err
}

const saveLastFMSession = `-- name: SaveLastFMSession :exec
UPDATE users
SET lastfm_session_name = ?,
    lastfm_session_key = ?
WHERE username = ?
`

type SaveLastFMSessionParams struct {
	LastfmSessionName sql.NullString
	LastfmSessionKey  sql.NullString
	Username          string
}

func (q *Queries) SaveLastFMSession(ctx context.Context, arg SaveLastFMSessionParams) error {
	_, err := q.db.ExecContext(ctx, saveLastFMSession, arg.LastfmSessionName, arg.LastfmSessionKey, arg.Username)
	return err
}

const saveSpotifySession = `-- name: SaveSpotifySession :exec
UPDATE users
SET spotify_access_token = ?,
    spotify_refresh_token = ?
WHERE username = ?
`

type SaveSpotifySessionParams struct {
	SpotifyAccessToken  sql.NullString
	SpotifyRefreshToken sql.NullString
	Username            string
}

func (q *Queries) SaveSpotifySession(ctx context.Context, arg SaveSpotifySessionParams) error {
	_, err := q.db.ExecContext(ctx, saveSpotifySession, arg.SpotifyAccessToken, arg.SpotifyRefreshToken, arg.Username)
	return err
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO users(username)
VALUES(?)
`

func (q *Queries) SaveUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, saveUser, username)
	return err
}

const updateSpotifyAccessToken = `-- name: UpdateSpotifyAccessToken :exec
UPDATE users
SET spotify_access_token = ?
WHERE username = ?
`

type UpdateSpotifyAccessTokenParams struct {
	SpotifyAccessToken sql.NullString
	Username           string
}

func (q *Queries) UpdateSpotifyAccessToken(ctx context.Context, arg UpdateSpotifyAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateSpotifyAccessToken, arg.SpotifyAccessToken, arg.Username)
	return err
}
