services:
  # proxy:
  #   image: caddy:latest
  #   restart: unless-stopped
  #   ports:
  #     - "3006:80"
  #     - "80:80"
  #     - "443:443"
  #     - "443:443/udp"
  #   volumes:
  #     - $PWD/Caddyfile:/etc/caddy/Caddyfile
  #   networks:
  #     - appwork
  nowplaying:
    build: .
    working_dir: /app
    environment:
      - PORT=8080
    env_file:
      - .env
    command: /usr/local/bin/nowplaying
    ports:
      - 3006:8080
    volumes:
      - $PWD:/app
#     networks:
#       appwork:
# networks:
#   appwork:
#     driver: bridge
