version: "3.7"

services:
  app:
    image: ghcr.io/cg219/nowplaying:main
    environment:
      - APP_DATA=data/database.db
      - NP_CREDTENTIALS=/run/secrets/npsecrets
      - APP_EXIT_BACKUP=1
      - PORT=8080
    ports:
      - 3006:8080
    volumes:
      - nowplaying-data:/app/data
    secrets:
      - npsecrets
  backup:
    image: ghcr.io/cg219/nowplaying:main
    environment:
      - APP_DATA=data/database.db
      - NP_CREDTENTIALS=/run/secrets/npsecrets
      - APP_EXIT_BACKUP=1
      - PORT=8081
    command: /usr/local/bin/backup
    volumes:
      - nowplaying-data:/app/data
    secrets:
      - npsecrets
    depends_on:
      app:
        condition: service_started
        restart: true

secrets:
  npsecrets:
    file: secrets.yml

volumes:
  nowplaying-data:
