version: "3.7"

services:
  app:
    image: ghcr.io/cg219/nowplaying:main
    environment:
      - APP_DATA=data/database.db
      - NP_CREDTENTIALS=/run/secrets/npsecrets
      - APP_EXIT_BACKUP=1
      - PORT=8080
    ports:
      - 3006:8080
    volumes:
      - nowplaying-data:/app/data
    secrets:
      - npsecrets
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
  backup:
    image: ghcr.io/cg219/nowplaying:main
    environment:
      - APP_DATA=data/database.db
      - NP_CREDTENTIALS=/run/secrets/npsecrets
      - APP_EXIT_BACKUP=1
      - PORT=8081
    command: ["/bin/sh", "-c", "while ! wget --spider -q http://nowplaying_app:8080/health; do sleep 2; done; /app/backup"]
    volumes:
      - nowplaying-data:/app/data
    secrets:
      - npsecrets
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  npsecrets:
    file: secrets.yml

volumes:
  nowplaying-data:
