lastfm:
  key: lastfm api key
  secret: lastfm api secret
turso:
  name: database name
  token: database token
  url: database url
spotify:
  id: client id
  secret: client secret
  redirect: redirect uri
youtube:
  key: api key
app:
  name: app username
